name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install Racket
      uses: Bogdanp/setup-racket@v1.6.1
      with:
        architecture: 'x64'
        distribution: 'full'
        version: '8.15'
    
    - name: Save version
      run: racket --version > .racket-version
      
    - name: Cache Racket dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/racket
          ~/.local/share/racket
        key: ${{ runner.os }}-racket-current-${{ hashFiles('.racket-version') }}

    - name: Install Dependencies
      run: raco pkg update rhombus-lib

    - name: Run Tests
      run: raco test test.rhm