name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install Racket
      uses: Bogdanp/setup-racket@v1.6.1
      with:
        architecture: 'x64'
        distribution: 'full'
        version: '8.8.0.5'
        packages: 'rhombus-lib'
        
    - name: Run Tests
      run: raco test test.rhm